# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: demo_development
  pool: 5
  username: root
  password: 123456
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: demo_test
  pool: 5
  username: root
  password: 123456

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: demo_production
  pool: 5
  username: root
  password: 123456
